FROM python:3.8.6-slim

WORKDIR /api

COPY ./services/worker/requirements.txt requirements.txt

RUN apt update && apt install git
RUN pip3 install -r requirements.txt

COPY . .

ENV CONF_FILE=conf.yaml

ENTRYPOINT ["python3", "_start_worker.py"]
